In [4]:
import pandas as pd
import numpy as np


mp = pd.read_csv('milk_production.csv')
mp.head()

,Category,State/ UT Name,Cow Milk-2010-11,Cow Milk-2011-12,Cow Milk-2013-14,Cow Milk-2014-15,Cow Milk-2015-16,Boffalo Milk-2010-11,Boffalo Milk-2011-12,Boffalo Milk-2013-14,Boffalo Milk-2014-15,Boffalo Milk-2015-16,Goat Milk-2010-11,Goat Milk-2011-12,Goat Milk-2013-14,Goat Milk-2014-15,Goat Milk-2015-16
0,State,Andhra Pradesh,3102.0,3377.0,3799.0,3079,3369,8101.0,8710.0,9207.0,6574,7445,1.0,1.0,1.0,3,3
1,State,Arunachal Pradesh,28.0,22.0,43.0,46,50,NaN,NaN,0.0,0,0,NaN,NaN,NaN,0,0
2,State,Assam,666.0,658.0,677.0,685,703,101.0,117.0,122.0,120,117,23.0,22.0,15.0,24,24
3,State,Bihar,3561.0,3661.0,3986.0,4318,4881,2798.0,2805.0,3015.0,3248,3210,158.0,177.0,196.0,209,198
4,State,Chhattisgarh,644.0,701.0,788.0,824,919,343.0,368.0,374.0,359,311,43.0,49.0,46.0,49,48

In [6]:
# Which state has produced max milk in year 2013-14?

mp['tot 13-14'] = mp.iloc[:,4]+mp.iloc[:,9]+mp.iloc[:,14]
mp[mp['tot 13-14']==mp['tot 13-14'].max()]

,Category,State/ UT Name,Cow Milk-2010-11,Cow Milk-2011-12,Cow Milk-2013-14,Cow Milk-2014-15,Cow Milk-2015-16,Boffalo Milk-2010-11,Boffalo Milk-2011-12,Boffalo Milk-2013-14,Boffalo Milk-2014-15,Boffalo Milk-2015-16,Goat Milk-2010-11,Goat Milk-2011-12,Goat Milk-2013-14,Goat Milk-2014-15,Goat Milk-2015-16,tot 13-14
26,State,Uttar Pradesh,5342.0,5837.0,6142.0,6387,8243,14496.0,15549.0,16805.0,17524,16865,1193.0,1171.0,1248.0,1288,1279,24195.0

In [10]:
# List top 5 milk producing states in each year from 2010 to 2015

mp['tot 10-11'] = mp.iloc[:,2]+mp.iloc[:,7]+mp.iloc[:,12]
mp['tot 11-12'] = mp.iloc[:,3]+mp.iloc[:,8]+mp.iloc[:,13]
mp['tot 14-15'] = mp.iloc[:,5]+mp.iloc[:,10]+mp.iloc[:,15]
print(mp[mp['tot 10-11']==mp['tot 10-11'].max()],'\n',mp[mp['tot 11-12']==mp['tot 11-12'].max()],'\n',mp[mp['tot 13-14']==mp['tot 13-14'].max()],'\n',mp[mp['tot 13-14']==mp['tot 13-14'].max()])

   Category State/ UT Name  Cow Milk-2010-11  Cow Milk-2011-12  \
26    State  Uttar Pradesh            5342.0            5837.0

    Cow Milk-2013-14  Cow Milk-2014-15  Cow Milk-2015-16  \
26            6142.0              6387              8243

    Boffalo Milk-2010-11  Boffalo Milk-2011-12  Boffalo Milk-2013-14  ...  \
26               14496.0               15549.0               16805.0  ...

    Boffalo Milk-2015-16  Goat Milk-2010-11  Goat Milk-2011-12  \
26                 16865             1193.0             1171.0

    Goat Milk-2013-14  Goat Milk-2014-15  Goat Milk-2015-16  tot 13-14  \
26             1248.0               1288               1279    24195.0

    tot 10-11  tot 11-12  tot 14-15
26    21031.0    22557.0      25199

[1 rows x 21 columns]
    Category State/ UT Name  Cow Milk-2010-11  Cow Milk-2011-12  \
26    State  Uttar Pradesh            5342.0            5837.0

    Cow Milk-2013-14  Cow Milk-2014-15  Cow Milk-2015-16  \
26            6142.0              6387              8243

    Boffalo Milk-2010-11  Boffalo Milk-2011-12  Boffalo Milk-2013-14  ...  \
26               14496.0               15549.0               16805.0  ...

    Boffalo Milk-2015-16  Goat Milk-2010-11  Goat Milk-2011-12  \
26                 16865             1193.0             1171.0

    Goat Milk-2013-14  Goat Milk-2014-15  Goat Milk-2015-16  tot 13-14  \
26             1248.0               1288               1279    24195.0

    tot 10-11  tot 11-12  tot 14-15
26    21031.0    22557.0      25199

[1 rows x 21 columns]
    Category State/ UT Name  Cow Milk-2010-11  Cow Milk-2011-12  \
26    State  Uttar Pradesh            5342.0            5837.0

    Cow Milk-2013-14  Cow Milk-2014-15  Cow Milk-2015-16  \
26            6142.0              6387              8243

    Boffalo Milk-2010-11  Boffalo Milk-2011-12  Boffalo Milk-2013-14  ...  \
26               14496.0               15549.0               16805.0  ...

    Boffalo Milk-2015-16  Goat Milk-2010-11  Goat Milk-2011-12  \
26                 16865             1193.0             1171.0

    Goat Milk-2013-14  Goat Milk-2014-15  Goat Milk-2015-16  tot 13-14  \
26             1248.0               1288               1279    24195.0

    tot 10-11  tot 11-12  tot 14-15
26    21031.0    22557.0      25199

[1 rows x 21 columns]
    Category State/ UT Name  Cow Milk-2010-11  Cow Milk-2011-12  \
26    State  Uttar Pradesh            5342.0            5837.0

    Cow Milk-2013-14  Cow Milk-2014-15  Cow Milk-2015-16  \
26            6142.0              6387              8243

    Boffalo Milk-2010-11  Boffalo Milk-2011-12  Boffalo Milk-2013-14  ...  \
26               14496.0               15549.0               16805.0  ...

    Boffalo Milk-2015-16  Goat Milk-2010-11  Goat Milk-2011-12  \
26                 16865             1193.0             1171.0

    Goat Milk-2013-14  Goat Milk-2014-15  Goat Milk-2015-16  tot 13-14  \
26             1248.0               1288               1279    24195.0

    tot 10-11  tot 11-12  tot 14-15
26    21031.0    22557.0      25199

[1 rows x 21 columns]

In [19]:
# Calculate average milk production by cow, buffalo and goat in each year for selected state.
st = input('Enter state\n')
r = mp[[mp['Category'] == 'State'] and mp['State/ UT Name']==st]

KeyboardInterrupt:

In [20]:
p = pd.read_csv('products.csv')

In [21]:
p.head()

,Year,Product line,Product type,Product,Order method type,Retailer country,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
0,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,United States,315044.33,437477.15,158371.76,66385.0,2.552857,6.59,156672.57,5.195714
1,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,Canada,13444.68,14313.48,6298.80,2172.0,2.900000,6.59,7145.88,6.190000
2,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,Japan,181120.24,235236.64,89413.06,35696.0,2.657000,6.59,91707.18,5.488000

In [23]:
# List all the products
p['Product'].unique()

array(['TrailChef Water Bag', 'TrailChef Canteen',
       'TrailChef Kitchen Kit', 'TrailChef Cup', 'TrailChef Cook Set',
       'TrailChef Deluxe Cook Set', 'TrailChef Single Flame',
       'TrailChef Double Flame', 'TrailChef Kettle', 'TrailChef Utensils',
       'Star Lite', 'Star Dome', 'Star Gazer 2', 'Star Gazer 3',
       'Star Gazer 6', 'Star Peg', 'Hibernator Lite', 'Hibernator',
       'Hibernator Extreme', 'Hibernator Self - Inflating Mat',
       'Hibernator Pad', 'Hibernator Pillow', 'Hibernator Camp Cot',
       'Canyon Mule Climber Backpack', 'Canyon Mule Weekender Backpack',
       'Canyon Mule Journey Backpack', 'Canyon Mule Extreme Backpack',
       'Canyon Mule Cooler', 'Canyon Mule Carryall', 'Firefly Lite',
       'Firefly Mapreader', 'Firefly 2', 'Firefly 4', 'Firefly Extreme',
       'Firefly Multi-light', 'EverGlow Single', 'EverGlow Double',
       'EverGlow Kerosene', 'EverGlow Butane', 'EverGlow Lamp',
       'Flicker Lantern', 'Mountain Man Analog', 'Mountain Man Digital',
       'Mountain Man Deluxe', 'Mountain Man Combination',
       'Mountain Man Extreme', 'Venue', 'Infinity', 'Lux', 'Sam', 'TX',
       'Legend', 'Kodiak', 'Zodiak', 'Polar Sun', 'Polar Ice',
       'Polar Sports', 'Polar Wave', 'Polar Extreme', 'Bella', 'Capri',
       'Cat Eye', 'Dante', 'Fairway', 'Inferno', 'Maximus', 'Trendi',
       'Zone', 'Hawk Eye', 'Retro', 'Single Edge', 'Double Edge',
       'Edge Extreme', 'Bear Edge', 'Bear Survival Edge', 'Max Gizmo',
       'Pocket Gizmo', 'Seeker 35', 'Seeker 50', 'Seeker Extreme',
       'Seeker Mini', 'Opera Vision', 'Ranger Vision', 'Glacier Basic',
       'Glacier Deluxe', 'Glacier GPS', 'Glacier GPS Extreme',
       'Trail Master', 'Trail Scout', 'Trail Star', 'Astro Pilot',
       'Sky Pilot', 'Auto Pilot', 'BugShield Natural', 'BugShield Spray',
       'BugShield Lotion Lite', 'BugShield Lotion', 'BugShield Extreme',
       'Sun Blocker', 'Sun Shelter Stick', 'Sun Shelter 15',
       'Sun Shelter 30', 'Sun Shield', 'Compact Relief Kit',
       'Deluxe Family Relief Kit', 'Calamine Relief', 'Aloe Relief',
       'Insect Bite Relief', 'Hailstorm Steel Irons',
       'Hailstorm Titanium Irons', 'Lady Hailstorm Steel Irons',
       'Lady Hailstorm Titanium Irons', 'Hailstorm Titanium Woods Set',
       'Hailstorm Steel Woods Set', 'Lady Hailstorm Titanium Woods Set',
       'Lady Hailstorm Steel Woods Set', 'Course Pro Putter',
       'Blue Steel Putter', 'Blue Steel Max Putter',
       'Course Pro Golf and Tee Set', 'Course Pro Umbrella',
       'Course Pro Golf Bag', 'Course Pro Gloves', 'Husky Rope 50',
       'Husky Rope 60', 'Husky Rope 100', 'Husky Rope 200',
       'Granite Climbing Helmet', 'Husky Harness',
       'Husky Harness Extreme', 'Granite Signal Mirror',
       'Granite Carabiner', 'Granite Belay', 'Granite Pulley',
       'Firefly Climbing Lamp', 'Firefly Charger',
       'Firefly Rechargeable Battery', 'Granite Chalk Bag', 'Granite Ice',
       'Granite Hammer', 'Granite Shovel', 'Granite Grip', 'Granite Axe',
       'Granite Extreme'], dtype=object)

In [25]:
# List all country names

p['Retailer country'].unique()

array(['United States', 'Canada', 'Mexico', 'Brazil', 'Japan', 'Korea',
       'China', 'Singapore', 'Australia', 'Netherlands', 'Sweden',
       'Finland', 'Denmark', 'France', 'Germany', 'United Kingdom',
       'Belgium', 'Switzerland', 'Austria', 'Italy', 'Spain'],
      dtype=object)

In [26]:
# List all order methods
p['Order method type'].unique()

array(['Telephone', 'Sales visit', 'Web', 'Special', 'Mail', 'E-mail',
       'Fax'], dtype=object)

In [30]:
# List the product which is able to sell maximum numbers in United States

p[p['Quantity'] == p[p['Retailer country']=='United States']['Quantity'].max()]

,Year,Product line,Product type,Product,Order method type,Retailer country,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
52227,2006,Personal Accessories,Eyewear,Zone,Web,United States,10054289.0,10054289.0,6756852.78,313628.0,21.661547,32.235823,3297436.22,32.235823

In [33]:
# Find the order method type which is able to sell more number of products in Germany

p[p['Quantity'] == p[p['Retailer country']=='Germany']['Quantity'].max()].loc[:,['Order method type']]

      Order method type
31073               Web

In [34]:
# List the top 5 products which has more gross profit in Australia
p[p['Retailer country']=='Australia'].sort_values(by='Gross profit', ascending = False)

,Year,Product line,Product type,Product,Order method type,Retailer country,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
58850,2006,Golf Equipment,Woods,Hailstorm Titanium Woods Set,Web,Australia,1298982.83,1386748.28,657378.00,1091.0,608.683333,1271.080000,641604.83,1196.936667
80018,2007,Golf Equipment,Woods,Hailstorm Titanium Woods Set,Web,Australia,1182182.89,1263453.52,606341.45,994.0,609.715000,1271.080000,575841.44,1189.733000
43856,2006,Camping Equipment,Tents,Star Lite,Web,Australia,1942609.77,2035344.87,1374750.00,5499.0,250.000000,370.130000,567859.77,354.264286
58409,2006,Golf Equipment,Irons,Hailstorm Titanium Irons,Web,Australia,904337.90,994455.63,469837.80,1071.0,441.882000,928.530000,434500.10,854.244000
79577,2007,Golf Equipment,Irons,Hailstorm Titanium Irons,Web,Australia,904802.19,994455.63,474286.74,1071.0,442.168000,928.530000,430515.45,844.959000
44150,2006,Camping Equipment,Tents,Star Gazer 2,Web,Australia,1471778.00,1549237.20,1044236.20,2660.0,392.570000,582.420000,427541.80,553.300000
65024,2007,Camping Equipment,Tents,Star Lite,Web,Australia,1338212.64,1395760.23,942750.00,3771.0,250.000000,370.130000,395462.64,358.350909
59144,2006,Golf Equipment,Woods,Lady Hailstorm Titanium Woods Set,Web,Australia,720785.34,758723.76,340380.00,558.0,610.000000,1359.720000,380405.34,1291.730000
80312,2007,Golf Equipment,Woods,Lady Hailstorm Titanium Woods Set,Web,Australia,697534.20,734248.80,329400.00,540.0,610.000000,1359.720000,368134.20,1291.730000
49295,2006,Personal Accessories,Watches,Infinity,Web,Australia,772106.60,772106.60,417953.84,3282.0,127.612500,235.821177,354152.76,235.821177
44003,2006,Camping Equipment,Tents,Star Dome,Web,Australia,971329.15,1014737.51,617364.00,1559.0,396.000000,650.890000,353965.15,623.356154
45032,2006,Camping Equipment,Sleeping Bags,Hibernator Extreme,Web,Australia,835446.90,876287.70,495750.00,3305.0,150.000000,265.140000,339696.90,254.721429
80165,2007,Golf Equipment,Woods,Hailstorm Steel Woods Set,Web,Australia,679539.60,707832.00,347407.20,1017.0,341.600000,696.000000,332132.40,671.640000
72962,2007,Personal Accessories,Eyewear,Inferno,Web,Australia,720813.95,720813.95,397890.37,10585.0,37.827835,68.371959,322923.58,68.371959
45914,2006,Camping Equipment,Packs,Canyon Mule Weekender Backpack,Web,Australia,820702.13,858813.56,500646.64,3004.0,166.660000,285.890000,320055.49,273.981667
58997,2006,Golf Equipment,Woods,Hailstorm Steel Woods Set,Web,Australia,681105.60,739152.00,362779.20,1062.0,341.600000,696.000000,318326.40,643.800000
51941,2006,Personal Accessories,Eyewear,Maximus,Web,Australia,610423.55,610423.55,301030.81,7148.0,41.942813,85.003438,309392.74,85.003438
52235,2006,Personal Accessories,Eyewear,Zone,Web,Australia,928170.20,928170.20,624489.54,28897.0,21.647778,32.162569,303680.66,32.162569
31067,2005,Personal Accessories,Eyewear,Zone,Web,Australia,939008.90,939008.90,636129.98,30611.0,20.790082,30.642787,302878.92,30.642787
46208,2006,Camping Equipment,Packs,Canyon Mule Extreme Backpack,Web,Australia,658354.32,687556.36,356647.84,1493.0,238.880000,460.520000,301706.48,442.425000
51794,2006,Personal Accessories,Eyewear,Inferno,Web,Australia,682699.75,682699.75,393791.38,10133.0,38.884962,67.252977,288908.37,67.252977
65318,2007,Camping Equipment,Tents,Star Gazer 2,Web,Australia,992620.20,1044861.48,704270.58,1794.0,392.570000,582.420000,288349.62,553.300000
49736,2006,Personal Accessories,Watches,TX,Web,Australia,633296.00,633296.00,346991.58,3465.0,101.960217,186.726594,286304.42,186.726594
58703,2006,Golf Equipment,Irons,Lady Hailstorm Titanium Irons,Web,Australia,561639.05,591198.30,279300.00,665.0,420.000000,889.020000,282339.05,844.570000
67229,2007,Camping Equipment,Packs,Canyon Mule Journey Backpack,Web,Australia,745970.26,811070.82,466552.71,2187.0,213.330000,370.860000,279417.55,335.835556
67082,2007,Camping Equipment,Packs,Canyon Mule Weekender Backpack,Web,Australia,698496.42,730163.06,425649.64,2554.0,166.660000,285.890000,272846.78,274.775556
79871,2007,Golf Equipment,Irons,Lady Hailstorm Titanium Irons,Web,Australia,535457.38,563638.68,266280.00,634.0,420.000000,889.020000,269177.38,844.570000
44297,2006,Camping Equipment,Tents,Star Gazer 3,Web,Australia,738045.36,776892.60,473976.00,1044.0,454.000000,744.150000,264069.36,706.940000
79430,2007,Golf Equipment,Irons,Hailstorm Steel Irons,Web,Australia,512724.20,534760.00,256360.00,1160.0,221.000000,461.000000,256364.20,444.865000
52529,2006,Personal Accessories,Eyewear,Retro,Web,Australia,558086.20,558086.20,306037.54,8908.0,34.366923,62.650000,252048.66,62.650000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83819,2007,Mountaineering Equipment,Tools,Granite Ice,Sales visit,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83861,2007,Mountaineering Equipment,Tools,Granite Ice,Special,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83882,2007,Mountaineering Equipment,Tools,Granite Ice,Mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83903,2007,Mountaineering Equipment,Tools,Granite Ice,E-mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83924,2007,Mountaineering Equipment,Tools,Granite Ice,Fax,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83966,2007,Mountaineering Equipment,Tools,Granite Hammer,Sales visit,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84008,2007,Mountaineering Equipment,Tools,Granite Hammer,Special,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84029,2007,Mountaineering Equipment,Tools,Granite Hammer,Mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84050,2007,Mountaineering Equipment,Tools,Granite Hammer,E-mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84071,2007,Mountaineering Equipment,Tools,Granite Hammer,Fax,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84113,2007,Mountaineering Equipment,Tools,Granite Shovel,Sales visit,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84155,2007,Mountaineering Equipment,Tools,Granite Shovel,Special,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84176,2007,Mountaineering Equipment,Tools,Granite Shovel,Mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84197,2007,Mountaineering Equipment,Tools,Granite Shovel,E-mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84218,2007,Mountaineering Equipment,Tools,Granite Shovel,Fax,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84260,2007,Mountaineering Equipment,Tools,Granite Grip,Sales visit,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84302,2007,Mountaineering Equipment,Tools,Granite Grip,Special,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84323,2007,Mountaineering Equipment,Tools,Granite Grip,Mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84344,2007,Mountaineering Equipment,Tools,Granite Grip,E-mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84365,2007,Mountaineering Equipment,Tools,Granite Grip,Fax,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84407,2007,Mountaineering Equipment,Tools,Granite Axe,Sales visit,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84449,2007,Mountaineering Equipment,Tools,Granite Axe,Special,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84470,2007,Mountaineering Equipment,Tools,Granite Axe,Mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84491,2007,Mountaineering Equipment,Tools,Granite Axe,E-mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84512,2007,Mountaineering Equipment,Tools,Granite Axe,Fax,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84554,2007,Mountaineering Equipment,Tools,Granite Extreme,Sales visit,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84596,2007,Mountaineering Equipment,Tools,Granite Extreme,Special,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84617,2007,Mountaineering Equipment,Tools,Granite Extreme,Mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84638,2007,Mountaineering Equipment,Tools,Granite Extreme,E-mail,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84659,2007,Mountaineering Equipment,Tools,Granite Extreme,Fax,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# Which order method is more popular (based on Quantity) world wide?
p[p['Quantity']==p['Quantity'].max()]['Order method type']

52227    Web
Name: Order method type, dtype: object

In [49]:
# Show the percentage of order methods for ‘Flicker Lantern’ in Denmark.
p[p['Product']=='Flicker Lantern' and p['Retailer country'] == 'Denmark']

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().